### ISSUE TITLE
Further Development with the Minetest Mods Team?

### ISSUE THREAD

**Issue by lnjX** [BlockMen/Wasteland#10]
This is a really nice game and it would be sad if it'll be so outdated that nobody wants to use it anymore!
I mean I would like to update many things and I know that BlockMen has left Minetest, so he won't do that. I don't want to do this for me (and my server) alone so I thought maybe we can do this all together! :smiley: 

So I ask you: @4Evergreen4 @Gael-de-Sailly @HybridDog @rubenwardy @Rui914 @sofar
Would it be ok to develop games in a mods-team? And would somebody fork this repo. into minetest-mods?

If not I'll create my own fork...

**Comment by rubenwardy** [comment]
Minetest-Mods isn't for subgames. Sofar suggested a sister org called Minetest-games

**Comment by lnjX** [comment]
Would be also nice.

**Comment by sofar** [comment]
I don't see as much of a need for games to be co-maintained by many people. Games are supersets of mods in almost all cases, so I would suggest forking and doing the maintenance yourself for a bit first.

**Comment by lnjX** [comment]
Okay.
