### ISSUE TITLE
NodeResolver error on v6 mapgen with particular seed

### ISSUE THREAD

**Issue by kozross** [BlockMen/Wasteland#5]
When I try make a new Wasteland (0.3) game using the v6 mapgen with the seed 'foo12bar15', I get this error upon world entry:

```
2015-11-21 23:01:24: ERROR[main]: NodeResolver: failed to resolve node name 'mapgen_river_water_source'.
```

This does not happen in the vanilla game. My Minetest version is 0.4.13.

**Comment by BlockMen** [comment]
There will be an update this year (i hope)? Until then you can easly fix it yourself by adding a line like this https://github.com/BlockMen/Wasteland/blob/master/mods/default/mapgen.lua#L14 for river_water

**Comment by BlockMen** [comment]
f7ed6e3c166074c33884ef8ba233f336dc0429c9
